name: mind_arena
description: A fast-paced, competitive mobile quiz game with real-time multiplayer functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  postgres: ^2.6.3
  dotenv: ^4.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  # Firebase packages
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  firebase_messaging: ^14.7.4
  google_sign_in: ^6.1.6
  # State management
  provider: ^6.0.5
  # UI enhancements
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  # Animation
  lottie: ^2.7.0
  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
